#!/bin/bash
# fsociety_vpn — Gateway Interface v1.6

if [ -z "$1" ] || [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
    cat << 'EOF'
===================================================================
d88888b .d8888.  .d88b.   .o88b. d888888b d88888b d888888b db    db
88'     88'  YP .8P  Y8. d8P  Y8   `88'   88         88    `8b  d8'
88ooo   `8bo.   88    88 8P         88    88oooooo   88     `8bd8'
88        `Y8b. 88    88 8b         88    88         88       88
88      db   8D `8b  d8' Y8b  d8   .88.   88.        88       88
YP      `8888Y'  `Y88P'   `Y88P' Y888888P Y88888P    YP       YP
===================================================================
Usage: fsociety [OPTIONS] <command> [args...]

Description:
  Runs the specified application inside the isolated AmneziaWG VPN namespace.
  Any [args...] provided will be passed directly to the target application.

Options:
  -h, --help    Show this help message and exit.
  --isolate     Run application in absolute isolation mode
                (Creates a fake HOME and disables D-Bus IPC)

Examples:
  fsociety Telegram                  # Runs Telegram through the secure tunnel
  fsociety curl ifconfig.me          # Checks the IP address of the VPN tunnel
  fsociety --isolate firefox         # Runs Firefox in isolated session
EOF
    exit 1
fi

REAL_USER=${SUDO_USER:-$USER}
USER_HOME=$(getent passwd "$REAL_USER" | cut -d: -f6)

ISOLATE=0
if [[ "$1" == "--isolate" ]]; then
    ISOLATE=1
    shift
    
    if [ -z "$1" ]; then
        echo "[-] fsociety error: No command specified for isolation."
        exit 1
    fi
fi

if ! command -v "$1" >/dev/null 2>&1; then
    echo "[-] fsociety error: Target '$1' does not exist in PATH."
    exit 1
fi

CMD_PATH=$(which "$1")
APP_NAME=$(basename "$1")

if [[ $ISOLATE -eq 1 ]]; then
    echo "[*] Initiating absolute isolation protocol for: $APP_NAME"
    
    ISOLATED_HOME="$USER_HOME/.fsociety_isolated/$APP_NAME"
    mkdir -p "$ISOLATED_HOME"
    
    sudo ip netns exec fsociety_mask sudo -E -u "$REAL_USER" env -u DBUS_SESSION_BUS_ADDRESS HOME="$ISOLATED_HOME" "$CMD_PATH" "${@:2}"
else
    sudo ip netns exec fsociety_mask sudo -E -u "$REAL_USER" env HOME="$USER_HOME" "$CMD_PATH" "${@:2}"
fi
